Repository AY2425S1-CS2113-T11-4/tp, pull requests merged in 2024-10, with the labels that each got.

#10 Implement add -d command
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/inventra/Inventra.java
  src/test/java/seedu/inventra/InventraTest.java
  tp/.idea/workspace.xml
Labels: priority.High

#11 Fix minor bug pertaining to Logo causing build errors
  src/main/java/seedu/inventra/Inventra.java
Labels: type.Bug, priority.Medium

#24 Fix bugs pertaining to duplicated fields and invalid file types on "add -h" command
  allJavaCode.txt
  inventory.csv
  src/main/java/seedu/command/AddCommand.java
  src/main/java/seedu/inventra/Inventra.java
  src/main/java/seedu/model/Inventory.java
  src/main/java/seedu/storage/inventory.csv
  src/main/java/seedu/ui/Ui.java
Labels: type.Bug, priority.High

#25 Implement update to csv after deleting records + Gradle fix
  allJavaCode.txt
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  src/main/java/seedu/command/DeleteCommand.java
  src/main/java/seedu/parser/CommandParser.java
  src/main/java/seedu/storage/Csv.java
  src/main/java/seedu/storage/inventory.csv
  src/main/java/seedu/ui/Ui.java
Labels: type.Enhancement, type.Bug

#28 Fix bugs pertaining to CSV Header
  src/main/java/seedu/command/AddCommand.java
  src/main/java/seedu/inventra/Inventra.java
  src/main/java/seedu/storage/Csv.java
  src/main/java/seedu/storage/inventory.csv
  src/test/java/seedu/inventra/InventraTest.java
Labels: type.Bug

#30 Fix test-setup to create test CSV file and handle file pathing
  src/test/java/seedu/inventra/InventraTest.java
Labels: type.Bug

#33 Delete headers and table
  src/main/java/seedu/command/AddCommand.java
  src/main/java/seedu/command/DeleteCommand.java
Labels: type.Enhancement

#39 Comment out unecessary debugging info
  src/main/java/seedu/storage/Csv.java
Labels: type.Enhancement

#41 Got rid of complex file path system
  .gitignore
  src/main/java/seedu/command/HelpCommand.java
  src/main/java/seedu/inventra/Inventra.java
  src/main/java/seedu/storage/Csv.java
  src/main/java/seedu/storage/inventory.csv
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/command/DeleteCommandTest.java
  src/test/java/seedu/inventra/InventraTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: type.Task

#42 Added command specific help
  src/main/java/seedu/command/HelpCommand.java
  src/main/java/seedu/parser/CommandParser.java
Labels: type.Task

#43 Delete range
  src/main/java/seedu/command/DeleteCommand.java
  src/main/java/seedu/command/HelpCommand.java
  src/test/java/seedu/command/DeleteCommandTest.java
Labels: type.Enhancement

#45 Enable assertion in build.gradle, removed add -l command
  allJavaCode.txt
  build.gradle
  src/main/java/seedu/command/AddCommand.java
  src/main/java/seedu/command/HelpCommand.java
  src/test/java/seedu/inventra/InventraTest.java
Labels: type.Task, priority.High

#55 Improve delete test
  src/main/java/seedu/command/DeleteCommand.java
  src/main/java/seedu/command/HelpCommand.java
  src/main/java/seedu/command/ViewCommand.java
  src/test/java/seedu/command/AddCommandTest.java
  src/test/java/seedu/command/DeleteCommandTest.java
Labels: type.Task
