Repository AY2425S1-CS2113-T11-4/tp, pull requests merged in 2024-11, with the labels that each got.

#61 Update Developer Guide to include UML diagrams and View command
  data/inventory.csv
  data/test_inventory.csv
  docs/uml/AddCommandArchitectureDiagram.puml
  docs/uml/AddCommandClassDiagram.puml
  docs/uml/AddCommandSequenceDiagram.puml
  docs/uml/Architecture.puml
  docs/uml/DeleteCommandArchitectureDiagram.puml
  docs/uml/DeleteCommandClassDiagram.puml
  docs/uml/DeleteCommandSequenceDiagram.puml
  docs/uml/ViewCommandArchitectureDiagram.puml
  docs/uml/ViewCommandClassDiagram.puml
  docs/uml/ViewCommandSequenceDiagram.puml
  docs/umldiagrams/AddCommandArchitectureDiagram.png
  docs/umldiagrams/AddCommandClassDiagram.png
  docs/umldiagrams/AddCommandSequenceDiagram.png
  docs/umldiagrams/ArchitectureDiagram.png
  docs/umldiagrams/DeleteCommandArchitectureDiagram.png
  docs/umldiagrams/DeleteCommandClassDiagram.png
  docs/umldiagrams/DeleteCommandSequenceDiagram.png
  docs/umldiagrams/ViewCommandArchitectureDiagram.png
  docs/umldiagrams/ViewCommandClassDiagram.png
  docs/umldiagrams/ViewCommandSequenceDiagram.png
Labels: type.Task

#63 Remove add -hu command and update README.md
  src/main/java/seedu/command/AddCommand.java
  src/test/java/seedu/command/AddCommandTest.java
Labels: type.Task

#64 Fix Gradle and CI test for AddCommand, ViewCommand, CommandParser Test
  src/main/java/seedu/command/AddCommand.java
  src/test/java/seedu/command/AddCommandTest.java
  src/test/java/seedu/command/ViewCommandTest.java
  src/test/java/seedu/parser/CommandParserTest.java
Labels: type.Bug, priority.High

#65 Enhance Coverage Testing for overall code base (Add, Delete, View)
  src/main/java/seedu/command/DeleteCommand.java
  src/main/java/seedu/command/ViewCommand.java
  src/test/java/seedu/command/AddCommandTest.java
  src/test/java/seedu/command/DeleteCommandTest.java
  src/test/java/seedu/command/ViewCommandTest.java
  src/test/java/seedu/inventra/InventraTest.java
  src/test/java/seedu/parser/CommandParserTest.java
Labels: type.Enhancement, type.Bug, priority.Medium

#66 Fix delete -h command to update CSV after deleting header
  src/main/java/seedu/command/DeleteCommand.java
Labels: type.Enhancement, type.Task

#70 Refactor codes identified with bugs upon Manual Test
  src/main/java/seedu/command/AddCommand.java
  src/main/java/seedu/command/DeleteCommand.java
  src/main/java/seedu/command/UpdateCommand.java
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/command/AddCommandTest.java
Labels: type.Task, type.Bug, priority.High

#72 Update landing page
  docs/README.md
  docs/UserGuide.md
Labels: type.Task

#146 V2.1 fix pe d #1
  docs/UserGuide.md
  src/main/java/seedu/command/AddCommand.java
  src/main/java/seedu/command/HelpCommand.java
  src/main/java/seedu/exceptions/InventraNegativeValueException.java
  src/test/java/seedu/command/AddCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High

#147 Address PE-D issues highlighted #2
  META-INF/MANIFEST.MF
  allJavaCode.txt
  app.log.1
  app.log.2
  src/main/java/seedu/command/ViewCommand.java
  src/main/java/seedu/exceptions/InventraOutOfBoundsException.java
  src/main/java/seedu/parser/CommandParser.java
  src/main/java/seedu/ui/Ui.java
  src/test/java/seedu/parser/CommandParserTest.java
Labels: type.Bug, priority.High

#150 Address PE-D issues highlighted #4
  app.log
  app.log.1
  app.log.lck
  data/inventory.csv
  data/new_inventory.csv
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/command/DeleteCommand.java
  test.csv
Labels: type.Enhancement, type.Bug, priority.High

#151 Address PE-D issues highlighted #5
  docs/UserGuide.md
  src/main/java/seedu/command/AddCommand.java
  src/main/java/seedu/command/UpdateCommand.java
  src/main/java/seedu/exceptions/InventraInvalidTypeException.java
  src/test/java/seedu/command/AddCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High

#154 Address issue #153 and included PPP
  app.log
  app.log.lck
  data/inventory.csv
  docs/team/tayjerom.md
  src/main/java/seedu/exceptions/InventraInvalidNumberException.java
Labels: type.Bug, priority.High

#155 Address issues raised in PE-D #6
  app.log
  docs/UserGuide.md
  src/main/java/seedu/command/UpdateCommand.java
  src/main/java/seedu/exceptions/InventraException.java
  src/main/java/seedu/exceptions/InventraLessArgsException.java
  src/main/java/seedu/inventra/Inventra.java
  src/main/java/seedu/storage/Csv.java
  src/test/java/seedu/command/UpdateCommandTest.java
Labels: type.Enhancement, type.Bug, priority.High

#156 Address PE-D issues highlighted #7
  allJavaCode.txt
  app.log
  app.log.1
  app.log.lck
  data/inventory.csv
  src/main/java/seedu/ui/Ui.java
Labels: type.Enhancement, type.Bug, priority.High

#166 Update PPP draft
  docs/team/johndoe.md
  docs/team/lucas-sc0.md
  src/main/java/seedu/command/AddCommand.java
Labels: priority.Low
